### ISSUE TITLE
Multigun Behavior

### ISSUE THREAD

**Issue by codemalone** [Computational-Worlds-Blue-One-Winter19/nukes-and-origami#123]
Multigun may not be loading/unloading correctly. I had times where five would load but appeared to be a three-count ring in front of a two-count ring. is this desirable?

also observed the multigun decrement and then I was left with no weapon.

**Comment by jim-rosales** [comment]
Is this still a bug??

**Comment by jim-rosales** [comment]
Thought nathan had fixed it

**Comment by codemalone** [comment]
Nathan has not posted a PR for this yet. Also, there are two bugs here the radius expansion could be a separate issue.

**Comment by jim-rosales** [comment]
Just pushed the fix for this in my open PR:https://github.com/Computational-Worlds-Blue-One-Winter19/nukes-and-origami/pull/125
