### ISSUE TITLE
Create homing missile

### ISSUE THREAD

**Issue by michaelosbornegit** [Computational-Worlds-Blue-One-Winter19/nukes-and-origami#69]

**Comment by michaelosbornegit** [comment]
For enemies: have a radius around the player when the bullet stops homing so the player can avoid it

For the player: The bullet will always hit the enemy.

**Comment by michaelosbornegit** [comment]
For the player it would be a single use powerup with an area of effect the destroys enemies around the enemy that was homed on

**Comment by codemalone** [comment]
Duplicate. See Issue #30
