### ISSUE TITLE
Add an invincible animation for the user's plane after it is hit

### ISSUE THREAD

**Issue by jim-rosales** [Computational-Worlds-Blue-One-Winter19/nukes-and-origami#8]
After the user's plane is hit it should blink for a given amount of time, 1 second for example.

**Comment by michaelosbornegit** [comment]
- on the update check for if the invincibility state is on or off and use that to drive if the plane gets hit or not and removes a life

**Comment by nathanfms** [comment]
completed, class Plane in ship.js change invincDuration to set how long the player will be invincible after begin hit. I think 2 seconds is fair.
