### ISSUE TITLE
targetPlayer ring firing config not working

### ISSUE THREAD

**Issue by michaelosbornegit** [Computational-Worlds-Blue-One-Winter19/nukes-and-origami#90]
Specifying targetPlayer: true in a rings firing config manifest does not cause bullets to target the player.

**Comment by codemalone** [comment]
I reverted to the old behavior for targetPlayer to aim each shot. I also added targetLeadShot to aim only once every round/pulse.

https://github.com/Computational-Worlds-Blue-One-Winter19/nukes-and-origami/commit/776e211a0b617983d13f6820746558ac4e618372
